### ISSUE TITLE
Configure Istio Tracing Backend

### ISSUE THREAD

**Issue by amybachir** [argoflow/argoflow-aws#144]
I'm trying to configure datadog tracing agent as istio's tracing backend. Where do I find this configuration?

**Comment by DavidSpek** [comment]
I've got this implemented already using Jaeger, but I still need to add it here.

**Comment by amybachir** [comment]
Thanks @DavidSpek any idea when you plan to add tracing config here? The more config flexibility the better, especially when it comes to istio.
