### ISSUE TITLE
Cluster Autoscaler is required in default settings with HA Redis

### ISSUE THREAD

**Issue by matty1979** [argoflow/argoflow-aws#15]
```
Install cluster autoscaler
kubectl apply -f https://raw.githubusercontent.com/kubernetes/autoscaler/master/cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml
```
Edit deployment
kubectl -n kube-system edit deployment.apps/cluster-autoscaler

Update autoscaler deployment flags
```
 - --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/<your eks cluster name>
 - --balance-similar-node-groups 
 - --skip-nodes-with-system-pods=false
 ```

**Comment by DavidSpek** [comment]
@matty1979 Is this related to the Argo CD deployment?

**Comment by DavidSpek** [comment]
@matty1979 I've added an Argo CD application spec for the cluster autoscaler in [this commit](https://github.com/argoflow/argoflow-aws/commit/1882249dff54c60dfdcec0234257b3178d08bd86). Could you please verify this works and solves the problem?

**Comment by matty1979** [comment]
This works correctly for cluster-auto-scaler and node termination handler. Both applied correctly via argo.
