### ISSUE TITLE
Spot Instances 

### ISSUE THREAD

**Issue by matty1979** [argoflow/argoflow-aws#16]
If Spot instances are used then this needs to be included 

Spot instance termination handler

```
helm repo add eks https://aws.github.io/eks-charts 
helm repo update 
helm install aws-node-termination-handler eks/aws-node-termination-handler \
--namespace kube-system \
--set enableSpotInterruptionDraining="true" \
--set enableScheduledEventDraining="true" \
--set nodeSelector.lifecycle=Ec2Spot
```

**Comment by DavidSpek** [comment]
Thanks for the information. This can be added to Argo CD as an application, which I'll look into.

**Comment by DavidSpek** [comment]
@matty1979 I've added an Argo CD application spec for the `aws-node-termination-handler` in [this commit](https://github.com/argoflow/argoflow-aws/commit/c0c99391bbcdb7fcaaf26805dcaf288ff53d2561), and also added it to the root `kustomization.yaml`. Could you please confirm that this application spec works?

**Comment by DavidSpek** [comment]
Closing this issue as I believe it was solved according to https://github.com/argoflow/argoflow-aws/issues/15#issuecomment-822638497. If not, please let me know and I will reopen.
