### ISSUE TITLE
aws-external-dns.yaml fails on Argocd

### ISSUE THREAD

**Issue by matty1979** [argoflow/argoflow-aws#20]
`Failed build model due to couldn't auto-discover subnets: unable to discover at least one subnet`

And 
`time="2021-04-19T17:20:35Z" level=fatal msg="flag parsing error: required flag --source not provided"`

**Comment by DavidSpek** [comment]
I'll look through the docs to try and find a solution tomorrow, unless you are able to find the solution before then.

**Comment by DavidSpek** [comment]
This was caused by an incorrect manifest which is now fixed.
