### ISSUE TITLE
setup_repo.sh errors 

### ISSUE THREAD

**Issue by matty1979** [argoflow/argoflow-aws#31]
On Mac OS 
`Darwin Kernel Version 20.3.0`

```
xargs: illegal option -- i
usage: xargs [-0opt] [-E eofstr] [-I replstr [-R replacements] [-S replsize]]
             [-J replstr] [-L number] [-n number [-x]] [-P maxprocs]
             [-s size] [utility [argument ...]]
```

Unable to run the setup_repo.sh command without numerous errors.

**Comment by GetOn4** [comment]
Added a PR for an extra Script that is valid on macos

**Comment by DavidSpek** [comment]
Closing this issue since it has been resolved by @GetOn4.

**Comment by matty1979** [comment]
Will test later today, but thank you!
